theme: jekyll-theme-dinky
title: OpenAPI Initiative Registry
description: Extensible data value repository
show_downloads: true
collections_dir: registry
collections:
  object:
    slug: object
    name: Object Registry
  format:
    slug: format
    name: Format Registry
    output: true
  extension:
    slug: extension
    name: Specification Extension Registry
    output: true
  draft-feature:
    slug: draft-feature
    name: Draft Features Registry
    output: true
  alternative-schema-type:
    slug: alternative-schema
    name: Alternative Schema Type Registry
    output: true
